### ISSUE TITLE
Exception from line 199 of "ExifPropertyAnnotator.php": Failed to parse time string

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#113]
### Setup

- MediaWiki 	1.31.1 (fe7ffa2) 21. Mär. 2019, 19:54
- PHP 	7.2.16 (cgi-fcgi)
- MariaDB 	10.1.38-MariaDB
- Semantic MediaWiki | 3.0.1
- Semantic Extra Special Properties | 2.0.0

### Configuration
```php
$sespgEnabledPropertyList = [
	'_EXIFDATA'
];
```

### Issue
```
[c521b6f89ebe063ad49a31b6] [no req]   Exception from line 199 of /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php: DateTime::__construct(): Failed to parse time string (2015:07:24 10:07:88) at position 4 (:): Unexpected character
```
This is what I got when running "rebuildData.php". I am not sure if SESP can do anything about this.

### Backtrace
```
#0 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(199): DateTime->__construct(string)
#1 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(176): SESP\PropertyAnnotators\ExifPropertyAnnotator->convertExifDate(string)
#2 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(169): SESP\PropertyAnnotators\ExifPropertyAnnotator->makeDataItemTime(string)
#3 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(141): SESP\PropertyAnnotators\ExifPropertyAnnotator->createDataItemFromExif(string, string, string, array, array)
#4 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(113): SESP\PropertyAnnotators\ExifPropertyAnnotator->addExifDataTo(SMW\DataModel\ContainerSemanticData, array)
#5 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(100): SESP\PropertyAnnotators\ExifPropertyAnnotator->getDataItemFromExifData(SMW\DIWikiPage, array)
#6 /../extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\ExifPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#7 /../extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#8 /../extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(172): SESP\ExtraPropertyAnnotator->addAnnotation(SMW\SemanticData)
#9 /../includes/Hooks.php(177): SESP\HookRegistry->SESP\{closure}(SMWSQLStore3, SMW\SemanticData)
#10 /../includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#11 /../extensions/SemanticMediaWiki/src/Store.php(223): Hooks::run(string, array)
#12 /../extensions/SemanticMediaWiki/src/DataUpdater.php(362): SMW\Store->updateData(SMW\SemanticData)
#13 /../extensions/SemanticMediaWiki/src/DataUpdater.php(222): SMW\DataUpdater->updateData()
#14 /../extensions/SemanticMediaWiki/src/DataUpdater.php(156): SMW\DataUpdater->performUpdate()
#15 /../extensions/SemanticMediaWiki/src/ParserData.php(468): SMW\DataUpdater->doUpdate()
#16 /../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(299): SMW\ParserData->updateStore()
#17 /../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(215): SMW\MediaWiki\Jobs\UpdateJob->updateStore(SMW\ParserData)
#18 /../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(136): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#19 /../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(93): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#20 /../extensions/SemanticMediaWiki/src/SQLStore/EntityRebuildDispatcher.php(209): SMW\MediaWiki\Jobs\UpdateJob->run()
#21 /../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(369): SMW\SQLStore\EntityRebuildDispatcher->rebuild(integer)
#22 /../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(307): SMW\Maintenance\DataRebuilder->do_update(integer)
#23 /../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(182): SMW\Maintenance\DataRebuilder->rebuild_all()
#24 /../extensions/SemanticMediaWiki/maintenance/rebuildData.php(167): SMW\Maintenance\DataRebuilder->rebuild()
#25 /../maintenance/doMaintenance.php(94): SMW\Maintenance\RebuildData->execute()
#26 /../extensions/SemanticMediaWiki/maintenance/rebuildData.php(225): require_once(string)
#27 {main}
```

**Comment by mwjames** [comment]
> DateTime::__construct(): Failed to parse time string (2015:07:24 10:07:88) at position 4 (:): Unexpected character

`:88` as seconds ??

- https://stackoverflow.com/questions/17427503/php-datetime-construct-failed-to-parse-time-string-xxxxxxxx-at-position-x

**Comment by kghbln** [comment]
> `:88` as seconds ??

I guess so, but it could also refer to `10:07:88` since it is split from the rest of the timestamp.

**Comment by mwjames** [comment]
> I guess so, but it could also refer to 10:07:88 since it is split from the rest of the timestamp.

It is not a `timestamp` it is a time string, also `ExifPropertyAnnotatorTest` as a test for it for this formatting.

For example, if you extend the test with:

```
		$provider[] = [
			[ 'DateTimeOriginal' => '2015:07:24 10:07:88' ],
			[ '_EXIF' => [ 'DATETIMEORIGINAL' => [ 'id' => 'Foo', 'type' => '_dat' ] ] ],
			$this->once()
		];
```
it fails but changing the seconds to:

```
		$provider[] = [
			[ 'DateTimeOriginal' => '2015:07:24 10:07:59' ],
			[ '_EXIF' => [ 'DATETIMEORIGINAL' => [ 'id' => 'Foo', 'type' => '_dat' ] ] ],
			$this->once()
		];
```
it will pass.

**Comment by kghbln** [comment]
Scheiße, how the ... can somebody upload a file with `:88` as seconds ?? I will have to find the transgressing file ...

**Comment by kghbln** [comment]
I am not sure how to access ID 2511. The lookup tells me that it is not in the database though "rebuildData.php" finds it every time I run it.

**Comment by mwjames** [comment]
> I am not sure how to access ID 2511. The lookup tells me that it is not in the database though "rebuildData.php" finds it every time I run it.

It is a subobject and is aborted before it is stored.

`ExifPropertyAnnotator` tells us it is about exif data that is retrieved from a file or picture which means we have to add something like:

```
@@ -171,11 +171,16 @@ class ExifPropertyAnnotator implements PropertyAnnotator {
 
 		return $dataItem;
 	}
 
 	private function makeDataItemTime( $exifValue ) {
-		$datetime = $this->convertExifDate( $exifValue );
+
+		try {
+			$datetime = $this->convertExifDate( $exifValue );
+		} catch ( \Exception $e ) {
+			$datetime = null;
+		}
```

and test against it with:

```
@@ -186,10 +186,17 @@ class ExifPropertyAnnotatorTest extends \PHPUnit_Framework_TestCase {
 			[ 'DateTimeOriginal' => '2013:01:11 02:13' ],
 			[ '_EXIF' => [ 'DATETIMEORIGINAL' => [ 'id' => 'Foo', 'type' => '_dat' ] ] ],
 			$this->once()
 		];
 
+		// #113
+		$provider[] = [
+			[ 'DateTimeOriginal' => '2015:07:24 10:07:88' ],
+			[ '_EXIF' => [ 'DATETIMEORIGINAL' => [ 'id' => 'Foo', 'type' => '_dat' ] ] ],
+			$this->never()
+		];
```

**Comment by kghbln** [comment]
The funny thing about this file is: 88 is it's size and it was uploaded in 2011. Not sure where the "2015:07:24" comes from.

**Comment by mwjames** [comment]
> The funny thing about this file is: 88 is it's size and it was uploaded in 2011. Not sure where the "2015:07:24" comes from.

`DateTime` is a PHP function and depending on the version used/in-use, the handling (errors etc.) can be different.

**Comment by kghbln** [comment]
Just checked the file with an exif view and it tells me that the file does not contain any exif data. :(

**Comment by mwjames** [comment]
> "2015:07:24" comes from.

To clarify, it is the `10:07:88` part that fails.

**Comment by mwjames** [comment]
> Just checked the file with an exif view and it tells me that the file does not contain any exif data. :(

It doesn't really matter, we encountered an issue where EXIF can contain invalid data (from the PHP validation point of view) and to avoid impairing the system, we should add above proposed changes.

**Comment by kghbln** [comment]
The main thing is that we can avoid this issue with the patch. I found many more files with similar issues which makes the script impossible to handle if not setting the --ignore-exceptions flag.

**Comment by kghbln** [comment]
Perfect. Just tested the proposed code change (https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/113#issuecomment-475866000) and "rebuildData.php" runs smoothly from start to end.
