### ISSUE TITLE
TypeError from line 267 of /includes/user/UserGroupManager.php

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticExtraSpecialProperties#156]
### Setup and configuration

Component|Version
-- | --
MediaWiki | 1.35.2
PHP | 7.3.28 (fpm-fcgi)
MariaDB | 10.3.29-MariaDB
ICU | 50.2
Semantic MediaWiki | 3.2.3 (5619c2d)
Semantic Extra Special Properties | 2.1.0 (01a45e4) 12:33, 9. Feb. 2020

### Issue
The rebuildData.php script of SMW throws occasional errors when SESP is active.

```
Notice: Undefined index: implicit in /includes/user/UserGroupManager.php on line 267
```
```
[743dc0983f7e9322b91a219c] [no req]   TypeError from line 267 of /includes/user/UserGroupManager.php: Return value of MediaWiki\User\UserGroupManager::getUserImplicitGroups() must be of the type array, null returned
```
#### Backtrace:
```
#0 /includes/user/UserGroupManager.php(295): MediaWiki\User\UserGroupManager->getUserImplicitGroups(User, integer, boolean)
#1 /includes/user/User.php(2972): MediaWiki\User\UserGroupManager->getUserEffectiveGroups(User, integer, boolean)
#2 /includes/Permissions/PermissionManager.php(1295): User->getEffectiveGroups()
#3 /includes/user/User.php(2927): MediaWiki\Permissions\PermissionManager->getUserPermissions(User)
#4 /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(82): User->getRights()
#5 /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageContributorsPropertyAnnotator.php(69): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->isNotAnonymous(User)
#6 /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\PageContributorsPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#7 /extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(SMW\DIProperty, SMW\SemanticData)
#8 /extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(176): SESP\ExtraPropertyAnnotator->addAnnotation(SMW\SemanticData)
#9 /includes/HookContainer/HookContainer.php(321): SESP\HookRegistry->SESP\{closure}(SMW\SQLStore\SQLStore, SMW\SemanticData)
#10 /includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook(string, array, array, array)
#11 /includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run(string, array, array)
#12 /extensions/SemanticMediaWiki/src/Store.php(230): Hooks::run(string, array)
#13 /extensions/SemanticMediaWiki/src/Store.php(271): SMW\Store->updateData(SMW\SemanticData)
#14 /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(98): SMW\Store->clearData(SMW\DIWikiPage)
#15 /extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(239): SMW\MediaWiki\Jobs\UpdateJob->run()
#16 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(470): SMW\SQLStore\Rebuilder\Rebuilder->rebuild(integer)
#17 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(383): SMW\Maintenance\DataRebuilder->doUpdateById(integer)
#18 /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#19 /extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#20 /maintenance/doMaintenance.php(107): SMW\Maintenance\rebuildData->execute()
#21 /extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#22 {main}
```

**Comment by kghbln** [comment]
I can confirm this issue for MW 1.35.3, PHP 7.4.3 and SESP 2.1.0

**Comment by krabina** [comment]
btw, my settings are

$sespgEnabledPropertyList = [
        '_EUSER',
        '_CUSER',
        '_EXIFDATA',
];
and rebuldData.php runs smootly on the same db when SESP is commented out in LocalSettins.php

**Comment by kghbln** [comment]
I believe this issue is only triggered for the identifies starting with `_USER` like `_USERREG` etc. If you do not have these you should not have an issue, which you confirmed in your post.

**Comment by kghbln** [comment]
Ah you commented out SESP. Well in this case you should not have an issue either but in the end it will be nice to use all identifiers provided by SESP. :)

**Comment by krabina** [comment]
Well it must be connected with EUSER and/or CUSER. These are the ones I set. If SESP is not present, it runs smoothly. If it is enabled, the errors show up.

**Comment by kghbln** [comment]
Ah, ok so it is connected to everything user.

**Comment by krabina** [comment]
Just tested it, if you just use 
```
$sespgEnabledPropertyList = [
        '_CUSER',
        '_EXIFDATA',
];
```
it is working. So indeed it is the EUSER

**Comment by kghbln** [comment]
This one is painful in a sense. This issue accounts for 95% of my error log file activity. A fix will be merciful.

**Comment by krabina** [comment]
Thank you very much, @26! Can you create a PR, please?
