### ISSUE TITLE
PHP Deprecated:  Use of InternalParseBeforeSanitize hook (used in VariablesHooks::onInternalParseBeforeSanitize) was deprecated in MediaWiki 1.35.

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#177]
### Setup and configuration

- MediaWiki | 1.37.1 (2aa4a86)18. Dez. 2021, 19:11
- PHP | 7.3.31-1~deb10u1 (apache2handler)
- MariaDB | 10.3.31-MariaDB-0+deb10u1
- Semantic MediaWiki | 4.0.0-rc1 (33cd750) 20. Dez. 2021, 14:08
- Semantic Extra Special Properties | 3.0.0-alpha (2250a16) 22. Nov. 2021, 12:07

### Issue

```
   ... 1 / 39 (  3%)     Attribut:Gehört_zu_Versionszweig
PHP Deprecated:  Use of InternalParseBeforeSanitize hook (used in VariablesHooks::onInternalParseBeforeSanitize) was deprecated in MediaWiki 1.35. [Called from MediaWiki\HookContainer\HookContainer::run in /var/www/htdocs/whn/00/01020/w/includes/HookContainer/HookContainer.php at line 137] in /var/www/htdocs/whn/00/01020/w/includes/debug/MWDebug.php on line 375
Wikimedia\Services\ContainerDisabledException from line 408 of /var/www/htdocs/whn/00/01020/w/vendor/wikimedia/services/src/ServiceContainer.php: Container disabled!
#0 /var/www/htdocs/whn/00/01020/w/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService('WikiPageFactory')
#1 /var/www/htdocs/whn/00/01020/w/includes/MediaWikiServices.php(1762): MediaWiki\MediaWikiServices->getService('WikiPageFactory')
#2 /var/www/htdocs/whn/00/01020/w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(193): MediaWiki\MediaWikiServices->getWikiPageFactory()
#3 /var/www/htdocs/whn/00/01020/w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/CreatorPropertyAnnotator.php(59): SESP\AppFactory->newWikiPage(Object(Title))
#4 /var/www/htdocs/whn/00/01020/w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\CreatorPropertyAnnotator->addAnnotation(Object(SMW\DIProperty), Object(SMW\SemanticData))
#5 /var/www/htdocs/whn/00/01020/w/extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(Object(SMW\DIProperty), Object(SMW\SemanticData))
#6 /var/www/htdocs/whn/00/01020/w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(178): SESP\ExtraPropertyAnnotator->addAnnotation(Object(SMW\SemanticData))
#7 /var/www/htdocs/whn/00/01020/w/includes/HookContainer/HookContainer.php(338): SESP\HookRegistry->SESP\{closure}(Object(SMW\SQLStore\SQLStore), Object(SMW\SemanticData))
#8 /var/www/htdocs/whn/00/01020/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook('SMWStore::updat...', Array, Array, Array)
#9 /var/www/htdocs/whn/00/01020/w/includes/Hooks.php(137): MediaWiki\HookContainer\HookContainer->run('SMWStore::updat...', Array, Array)
#10 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/Store.php(230): Hooks::run('SMWStore::updat...', Array)
#11 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/DataUpdater.php(418): SMW\Store->updateData(Object(SMW\SemanticData))
#12 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/DataUpdater.php(297): SMW\DataUpdater->updateData()
#13 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/DataUpdater.php(197): SMW\DataUpdater->runUpdate()
#14 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/ParserData.php(468): SMW\DataUpdater->doUpdate()
#15 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(303): SMW\ParserData->updateStore()
#16 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(216): SMW\MediaWiki\Jobs\UpdateJob->updateStore(Object(SMW\ParserData))
#17 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(137): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#18 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#19 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(193): SMW\MediaWiki\Jobs\UpdateJob->run()
#20 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/Maintenance/DistinctEntityDataRebuilder.php(170): SMW\Maintenance\DistinctEntityDataRebuilder->doUpdate(Object(SMW\MediaWiki\JobFactory), Object(Title))
#21 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(267): SMW\Maintenance\DistinctEntityDataRebuilder->doRebuild()
#22 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(318): SMW\Maintenance\DataRebuilder->rebuildFromSelection(Array)
#23 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(222): SMW\Maintenance\DataRebuilder->rebuildAll()
#24 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#25 /var/www/htdocs/whn/00/01020/w/maintenance/doMaintenance.php(108): SMW\Maintenance\rebuildData->execute()
#26 /var/www/htdocs/whn/00/01020/w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once('/var/www/htdocs...')
#27 {main}
```

**Comment by kghbln** [comment]
Duplicate of https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/168
