### ISSUE TITLE
TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given

### ISSUE THREAD

**Issue by krabina** [SemanticMediaWiki/SemanticExtraSpecialProperties#226]
### Setup and configuration

- SMW version: 4.1.3
- SESP version: 3.0.5
- MW version: 1.39.7
- PHP version: 8
- DB (MySQL etc. and version):

### Issue

rebuildData.php produces an error on some pages:

```
TypeError: preg_match(): Argument #2 ($subject) must be of type string, array given
Backtrace:
from 
* /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(203)
#0  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(203): preg_match()
#1  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(178): SESP\PropertyAnnotators\ExifPropertyAnnotator->convertExifDate()
#2  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(169): SESP\PropertyAnnotators\ExifPropertyAnnotator->makeDataItemTime()
#3  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(141): SESP\PropertyAnnotators\ExifPropertyAnnotator->createDataItemFromExif()
#4  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(113): SESP\PropertyAnnotators\ExifPropertyAnnotator->addExifDataTo()
#5  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/ExifPropertyAnnotator.php(100): SESP\PropertyAnnotators\ExifPropertyAnnotator->getDataItemFromExifData()
#6  /extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\ExifPropertyAnnotator->addAnnotation()
#7  /extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation()
#8  /extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(178): SESP\ExtraPropertyAnnotator->addAnnotation()
#9  /includes/HookContainer/HookContainer.php(338): SESP\HookRegistry->SESP\{closure}()
#10  /includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#11  /extensions/SemanticMediaWiki/src/Store.php(235): MediaWiki\HookContainer\HookContainer->run()
#12  /extensions/SemanticMediaWiki/src/DataUpdater.php(420): SMW\Store->updateData()
#13  /extensions/SemanticMediaWiki/src/DataUpdater.php(297): SMW\DataUpdater->updateData()
#14  /extensions/SemanticMediaWiki/src/DataUpdater.php(197): SMW\DataUpdater->runUpdate()
#15  /extensions/SemanticMediaWiki/src/ParserData.php(469): SMW\DataUpdater->doUpdate()
#16  /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(305): SMW\ParserData->updateStore()
#17  /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(218): SMW\MediaWiki\Jobs\UpdateJob->updateStore()
#18  /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(139): SMW\MediaWiki\Jobs\UpdateJob->parse_content()
#19  /extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(94): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#20  /extensions/SemanticMediaWiki/src/SQLStore/Rebuilder/Rebuilder.php(247): SMW\MediaWiki\Jobs\UpdateJob->run()
#21  /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(472): SMW\SQLStore\Rebuilder\Rebuilder->rebuild()
#22  /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(385): SMW\Maintenance\DataRebuilder->doUpdateById()
#23  /extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(224): SMW\Maintenance\DataRebuilder->rebuildAll()
#24  /extensions/SemanticMediaWiki/maintenance/rebuildData.php(198): SMW\Maintenance\DataRebuilder->rebuild()
#25  /maintenance/includes/MaintenanceRunner.php(309): SMW\Maintenance\rebuildData->execute()
#26  /maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
#27  /extensions/SemanticMediaWiki/maintenance/rebuildData.php(294): require_once(string)
#28 {main}

```

Steps to reproduce the observation (recommendation is to use the [sandbox](https://sandbox.semantic-mediawiki.org)):

**Comment by krabina** [comment]
the --ignore-exceptions option does not work in this case

**Comment by kghbln** [comment]
I can confirm this for the following setup:


- [MediaWiki](https://www.mediawiki.org/) 	[1.39.7](https://www.mediawiki.org/wiki/MediaWiki_1.39) [(2ba7e95)](https://gerrit.wikimedia.org/g/mediawiki/core.git/+/2ba7e95b066ca107bea9b0588a0a381b353611ea) 13 mei 2024 11:45
- [PHP](https://php.net/) 	8.1.2-1ubuntu2.17 (apache2handler)
- [MariaDB](https://mariadb.org/) 	10.6.16-MariaDB-0ubuntu0.22.04.1
- [ICU](https://icu.unicode.org/) 	70.1
- [Semantic MediaWiki](https://www.semantic-mediawiki.org/)	4.1.3
- [Semantic Extra Special Properties](https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/)	3.0.5

**Comment by malberts** [comment]
Still reproduces on current versions, and here is the root cause plus a minimal repro.

**Confirmed on:** SESP 5.0.0, SMW 7.2.0, MediaWiki 1.43.8, PHP 8.3.31. Same crash, now at `ExifPropertyAnnotator.php:205` (was `:203` in 3.0.5). Unchanged on `master` (the `_dat` / `convertExifDate` path has only had formatting/API-migration commits since).

**Root cause.** The trigger is a File page whose image carries an XMP `dc:date`. `dc:date` is Dublin Core, and it is legitimately a *multi-valued* XMP sequence, so MediaWiki stores it as an array rather than a scalar, e.g.:

```
$file->getMetadataArray()['dc-date'] === [ 0 => '2025:11:03 21:27:42', '_type' => 'ol' ]
```

SESP's `data/definitions.json` maps `dc-date` to an Exif date property (`___EXIFDC-DATE`, type `_dat`, label `Exif:Dc-date`). The `_dat` branch of `createDataItemFromExif()` assumes a scalar string and passes the value straight into `convertExifDate()`, which calls `preg_match( $pattern, $rawDate )`. With the array value, `preg_match()` throws a `TypeError` (PHP 8). That is an `\Error`, so the `catch ( \Exception )` around the date parse does not catch it; it propagates out and aborts the whole page's SMW data update (and, under `rebuildData`, the maintenance run). The dates themselves are valid, only the array shape is unhandled.

**Minimal repro** (no special image needed):

```
convert -size 64x64 xc:blue dcdate.jpg
exiftool -XMP-dc:Date="2025-11-03T21:27:42" dcdate.jpg
```

Upload `dcdate.jpg` on a wiki with `$sespgEnabledPropertyList = [ '_EXIFDATA' ]`, then reparse or `rebuildData --page "File:Dcdate.jpg"`. It crashes as above. This is not synthetic-only: it was originally hit by ordinary uploaded photos whose XMP carried a `dc:date`.

A trigger file is already uploaded to the SMW sandbox (SESP 5.0.0 / SMW 7.2.1-alpha / MediaWiki 1.43.9 / PHP 8.2): https://sandbox.semantic-mediawiki.net/wiki/File:Dcdate-repro.jpg . MediaWiki stored its `dc-date` as `[ 0 => '2025:11:03 21:27:42', '_type' => 'ol' ]`, and `rebuildData --page "File:Dcdate-repro.jpg"` should reproduce the fatal there directly. (The sandbox is reset periodically, so the recipe above is the durable repro.)

**Fix direction.** In the `_dat` handling, when the raw value is a sequence array, extract the scalar element (the `0` key) before the string date-parse, rather than only broadening the caught type.

<sub>AI-authored: Claude Code, `Opus 4.8`; root-caused and reproduced end-to-end for @malberts on a clean SESP 5.0.0 / SMW 7.2.0 / MediaWiki 1.43.8 install (PHP 8.3.31) with the generated JPEG above.</sub>
