### ISSUE TITLE
Invalid or virtual namespace -1 given.

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#54]
* MW: 1.25.3
* SMW: 2.3.0
* SESP: 1.3.1
* PHP: 5.6.11
* SQL: 5.6.27

```
(7924/32741) Processing ID 8093 ...
[ab886719] [no req]   MWException from line 111 of /.../includes/page/WikiPage.php: Invalid or virtual namespace -1 given.
Backtrace:
#0 /.../extensions/SemanticExtraSpecialProperties/src/AppFactory.php(45): WikiPage::factory(Title)
#1 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(95): SESP\AppFactory->newWikiPage(Title)
#2 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(199): SESP\Annotator\ExtraPropertyAnnotator->getWikiPage()
#3 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(146): SESP\Annotator\ExtraPropertyAnnotator->makeFirstAuthorDataItem()
#4 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(120): SESP\Annotator\ExtraPropertyAnnotator->createDataItemById(string, SMW\DIProperty)
#5 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(72): 
SESP\Annotator\ExtraPropertyAnnotator->addPropertyValues()
#6 /.../extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(101): SESP\Annotator\ExtraPropertyAnnotator->addAnnotation()
#7 [internal function]: SESP\HookRegistry->SESP\{closure}(SMWSQLStore3, SMW\SemanticData)
#8 /.../includes/Hooks.php(207): call_user_func_array(Closure, array)
#9 /.../includes/GlobalFunctions.php(3970): Hooks::run(string, array, NULL)
#10 /.../extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(218): wfRunHooks(string, array)
#11 /.../extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(243): SMW\Store->updateData(SMW\SemanticData)
#12 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(93): SMW\Store->clearData(SMW\DIWikiPage)
#13 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#14 /.../extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#15 /.../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#16 /.../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#17 /.../extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#18 /.../maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#19 /.../extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#20 {main}
```
It may well be that SESP is the spot where it becomes apparent though the actual issue is caused elsewhere.

**Comment by mwjames** [comment]
> WikiPage.php: Invalid or virtual namespace -1 given.

Normally indicates a `SpecialPage`. What says the [OBJECT ID lookup](https://www.semantic-mediawiki.org/wiki/Help:Object_ID_lookup) about `8093`?

**Comment by kghbln** [comment]
It does:
```
[
    8093,
    {
        "smw_title": "Ask/-5B-5BNews-20date::+-5D-5D-20-5B-5Blanguage-20code::en-5D-5D/format=feed/sort=news-20date/order=descending/searchlabel=-20RSS-20feed-20example/type=rss/title=Semantic-20MediaWiki/description=Latest-20news-20from-20semantic-2Dmediawiki.org/offset=0",
        "smw_namespace": "-1",
        "smw_iw": "",
        "smw_subobject": ""
    }
]
```

**Comment by mwjames** [comment]
I see a pattern here, an annotation was created by some with the value of `Special:"Ask/-5B-5BNews-20date::+-5D-5D-20-5B-5Blanguage-20code::en-5D-5D/format=feed/sort=news-20date/order=descending/searchlabel=-20RSS-20feed-20example/type=rss/title=Semantic-20MediaWiki/description=Latest-20news-20from-20semantic-2Dmediawiki.org/offset=0` which causes the issue.

**Comment by mwjames** [comment]
One down 62d3889.

**Comment by kghbln** [comment]
:+1:

**Comment by kghbln** [comment]
### Setup and configuration

- MediaWiki 	1.27.1 (8c593e7) 22:49, 26 October 2016
- PHP 	7.0.13-0ubuntu0.16.04.1 (apache2handler)
- MySQL 	5.7.16-0ubuntu0.16.04.1
- Semantic MediaWiki	2.4.5 (59d5cf0) 15:06, 16 January 2017
- Semantic Extra Special Properties	1.3.1 (8b2c8b2) 17:01, 18 July 2015

### Issue
Then running maintenance script "rebuildData.php" just with the `-v` flag the following issue arises:

(6816/56397)    Finished processing ID 8093 (Category:Listwidget_examples)
[c7df5625887bc65f11b178b7] [no req]   MWException from line 105 of /.../w/includes/page/WikiPage.php: Invalid or virtual namespace -1 given.

This is quite painful.

### Backtrace
```
#0 /.../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(45): WikiPage::factory(Title)
#1 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(95): SESP\AppFactory->newWikiPage(Title)
#2 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(199): SESP\Annotator\ExtraPropertyAnnotator->getWikiPage()
#3 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(146): SESP\Annotator\ExtraPropertyAnnotator->makeFirstAuthorDataItem()
#4 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(120): SESP\Annotator\ExtraPropertyAnnotator->createDataItemById(string, SMW\DIProperty)
#5 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(72): SESP\Annotator\ExtraPropertyAnnotator->addPropertyValues()
#6 /.../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(101): SESP\Annotator\ExtraPropertyAnnotator->addAnnotation()
#7 /.../w/includes/Hooks.php(195): SESP\HookRegistry->SESP\{closure}(SMWSQLStore3, SMW\SemanticData)
#8 /.../w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(246): Hooks::run(string, array)
#9 /.../w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(267): SMW\Store->updateData(SMW\SemanticData)
#10 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(91): SMW\Store->clearData(SMW\DIWikiPage)
#11 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(56): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#12 /.../w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(191): SMW\MediaWiki\Jobs\UpdateJob->run()
#13 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(307): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#14 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(266): SMW\Maintenance\DataRebuilder->doExecuteFor(SMW\SQLStore\ByIdDataRebuildDispatcher, integer)
#15 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(167): SMW\Maintenance\DataRebuilder->doRebuildAll()
#16 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(149): SMW\Maintenance\DataRebuilder->rebuild()
#17 /.../w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#18 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(197): require_once(string)
#19 {main}
```

**Comment by kghbln** [comment]
> This is quite painful.

Ah, I just see that we have not done a new release for a while. I guess it will be nice to do the 1.4 release soon. 

@mwjames Objections? Do we need something else in it that has not been done yet.

**Comment by kghbln** [comment]
I will now re-run "rebuildData.php" with master of SESP to make sure that everything is in fluff.

**Comment by kghbln** [comment]
Yep, everything is fluffy now. 

```bash
32212 IDs refreshed.

Memory used: 74327000 (b: 13666992, a: 87993992) with a runtime of 3653.95 sec (60.9 min)
```

**Comment by mwjames** [comment]
> Objections? Do we need something else in it that has not been done yet.

No.

**Comment by kghbln** [comment]
Well, disaster is always waiting to unfold. Yesterday I switched to weekly at Saturday "rebuildData.php" runs via cron and this is how the script exited tonight:

```
[2e6def31c08f88f164968e15] [no req]   MWException from line 105 of /.../w/includes/page/WikiPage.php: Invalid or virtual namespace -1 given.
Backtrace:
#0 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(107): WikiPage::factory(Title)
#1 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(82): SMW\MediaWiki\Jobs\UpdateJob->matchWikiPageLastModifiedToRevisionLastModified(Title)
#2 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(56): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#3 /.../w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(191): SMW\MediaWiki\Jobs\UpdateJob->run()
#4 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(307): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#5 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(266): SMW\Maintenance\DataRebuilder->doExecuteFor(SMW\SQLStore\ByIdDataRebuildDispatcher, integer)
#6 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(167): SMW\Maintenance\DataRebuilder->doRebuildAll()
#7 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(149): SMW\Maintenance\DataRebuilder->rebuild()
#8 /.../w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#9 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(197): require_once(string)
#10 {main}
```
So there is still something in the water.

**Setup**

- MediaWiki 	1.27.1 (8c593e7) 22:49, 26 October 2016
- PHP 	7.0.13-0ubuntu0.16.04.1 (apache2handler)
- MySQL 	5.7.17-0ubuntu0.16.04.1
- Semantic MediaWiki	2.4.5 (59d5cf0) 15:06, 16 January 2017
- Semantic Extra Special Properties	1.4.0-alpha (a1540c4) 05:45, 19 January 2017

**Comment by mwjames** [comment]
> Backtrace:
#0 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(107): WikiPage::factory(Title)
#1 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(82): SMW\MediaWiki\Jobs\UpdateJob->matchWikiPageLastModifiedToRevisionLastModified(Title)

Isn't that great, we have to test the `Title` in `UpdateJob`.

**Comment by mwjames** [comment]
If you copy the report to SMW-core then I'll try to post a check for it.
