### ISSUE TITLE
NS_MEDIA is a virtual namespace; use NS_FILE

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticExtraSpecialProperties#55]
* MW: 1.25.3
* SMW: 2.3.0
* SESP: 1.3.1
* PHP: 5.6.11
* SQL: 5.6.27

```
(218/35024) Processing ID 10139 ...
[bc0e5f60] [no req]   MWException from line 109 of /.../includes/page/WikiPage.php: NS_MEDIA is a virtual namespace; use NS_FILE.
Backtrace:
#0 /.../extensions/SemanticExtraSpecialProperties/src/AppFactory.php(45): WikiPage::factory(Title)
#1 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(95): SESP\AppFactory->newWikiPage(Title)
#2 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(199): SESP\Annotator\ExtraPropertyAnnotator->getWikiPage()
#3 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(146): SESP\Annotator\ExtraPropertyAnnotator->makeFirstAuthorDataItem()
#4 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(120): SESP\Annotator\ExtraPropertyAnnotator->createDataItemById(string, SMW\DIProperty)
#5 /.../extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(72): SESP\Annotator\ExtraPropertyAnnotator->addPropertyValues()
#6 /.../extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(101): SESP\Annotator\ExtraPropertyAnnotator->addAnnotation()
#7 [internal function]: SESP\HookRegistry->SESP\{closure}(SMWSQLStore3, SMW\SemanticData)
#8 /.../includes/Hooks.php(207): call_user_func_array(Closure, array)
#9 /.../includes/GlobalFunctions.php(3970): Hooks::run(string, array, NULL)
#10 /.../extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(218): wfRunHooks(string, array)
#11 /.../extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(243): SMW\Store->updateData(SMW\SemanticData)
#12 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(93): SMW\Store->clearData(SMW\DIWikiPage)
#13 /.../extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#14 /.../extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#15 /.../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#16 /.../extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#17 /.../extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#18 /.../maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#19 /.../extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#20 {main}
```
It may well be that SESP is the spot where it becomes apparent though the actual issue is caused elsewhere.

**Comment by mwjames** [comment]
> WikiPage.php: NS_MEDIA is a virtual namespace; use NS_FILE.

WTF, this used to work !!!!

**Comment by kghbln** [comment]
> WTF, this used to work !!!!

This issue somehow sounded familiar to me, was not sure though. :(

**Comment by mwjames** [comment]
`makeFirstAuthorDataItem` tries to get `$this->page = $this->appFactory->newWikiPage( $this->semanticData->getSubject()->getTitle() );` so this makes no sense.

Object ID data on `10139`?

**Comment by kghbln** [comment]
There are heaps of these around, this is just one of them:
```
[
    10139,
    {
        "smw_title": "20121026_SMWCon_Fall_Hans_de_Bruin_Brain-Inspired_Expertise_Management.pdf",
        "smw_namespace": "-2",
        "smw_iw": "",
        "smw_subobject": ""
    }
]
```

**Comment by mwjames** [comment]
According to [0]. ????!!!!????

6	File	NS_FILE
-2	Media	NS_MEDIA

A manual edit of [1] keeps the -2 namespace.

[0] https://www.mediawiki.org/wiki/Manual:Namespace_constants

[1] https://www.semantic-mediawiki.org/wiki/File:20121026_SMWCon_Fall_Hans_de_Bruin_Brain-Inspired_Expertise_Management.pdf

**Comment by mwjames** [comment]
@kghbln https://phabricator.wikimedia.org/T39131 relevant?

**Comment by kghbln** [comment]
> Apparently the problem is resolved clearing data in table l10n_cache: after purging all data from that table MediaWiki works again.

Will test.

**Comment by kghbln** [comment]
> Will test.

Sorry that this took too long again:

undisclosed wiki with this issue: Clearing `I10n_cache` did not help since this table was empty from the start. The particular and only file creating this issue was just uploaded and then embedded on a wiki page [[File:Xyz....]] as well as an link to [[Media:Xyz...]] was added to the same page.

swm.o with this issue: Now I get:
```
(1/39734) Processing ID 8095 ...
[c3033f64] [no req]   MWException from line 111 of /.../w/includes/page/WikiPage.php: Invalid or virtual namespace -1 given.
Backtrace:
#0 /.../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(45): WikiPage::factory(Title)
#1 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(95): SESP\AppFactory->newWikiPage(Title)
#2 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(199): SESP\Annotator\ExtraPropertyAnnotator->getWikiPage()
#3 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(146): SESP\Annotator\ExtraPropertyAnnotator->makeFirstAuthorDataItem()
#4 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(120): SESP\Annotator\ExtraPropertyAnnotator->createDataItemById(string, SMW\DIProperty)
#5 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(72): SESP\Annotator\ExtraPropertyAnnotator->addPropertyValues()
#6 /.../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(101): SESP\Annotator\ExtraPropertyAnnotator->addAnnotation()
#7 [internal function]: SESP\HookRegistry->SESP\{closure}(SMWSQLStore3, SMW\SemanticData)
#8 /.../w/includes/Hooks.php(207): call_user_func_array(Closure, array)
#9 /.../w/includes/GlobalFunctions.php(3970): Hooks::run(string, array, NULL)
#10 /.../w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(218): wfRunHooks(string, array)
#11 /.../w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(243): SMW\Store->updateData(SMW\SemanticData)
#12 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(93): SMW\Store->clearData(SMW\DIWikiPage)
#13 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#14 /.../w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#15 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#16 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#17 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#18 /.../w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#19 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#20 {main}
```
Edit: No the original error still persist too, e.g. 
```
(218/39734) Processing ID 10139 ...
[cac004b9] [no req]   MWException from line 109 of /.../w/includes/page/WikiPage.php: NS_MEDIA is a virtual namespace; use NS_FILE.
Backtrace:
#0 /.../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(45): WikiPage::factory(Title)
#1 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(95): SESP\AppFactory->newWikiPage(Title)
#2 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(199): SESP\Annotator\ExtraPropertyAnnotator->getWikiPage()
#3 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(146): SESP\Annotator\ExtraPropertyAnnotator->makeFirstAuthorDataItem()
#4 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(120): SESP\Annotator\ExtraPropertyAnnotator->createDataItemById(string, SMW\DIProperty)
#5 /.../w/extensions/SemanticExtraSpecialProperties/src/Annotator/ExtraPropertyAnnotator.php(72): SESP\Annotator\ExtraPropertyAnnotator->addPropertyValues()
#6 /.../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(101): SESP\Annotator\ExtraPropertyAnnotator->addAnnotation()
#7 [internal function]: SESP\HookRegistry->SESP\{closure}(SMWSQLStore3, SMW\SemanticData)
#8 /.../w/includes/Hooks.php(207): call_user_func_array(Closure, array)
#9 /.../w/includes/GlobalFunctions.php(3970): Hooks::run(string, array, NULL)
#10 /.../w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(218): wfRunHooks(string, array)
#11 /.../w/extensions/SemanticMediaWiki/includes/storage/SMW_Store.php(243): SMW\Store->updateData(SMW\SemanticData)
#12 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(93): SMW\Store->clearData(SMW\DIWikiPage)
#13 /.../w/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/UpdateJob.php(57): SMW\MediaWiki\Jobs\UpdateJob->doUpdate()
#14 /.../w/extensions/SemanticMediaWiki/src/SQLStore/ByIdDataRebuildDispatcher.php(171): SMW\MediaWiki\Jobs\UpdateJob->run()
#15 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(247): SMW\SQLStore\ByIdDataRebuildDispatcher->dispatchRebuildFor(integer)
#16 /.../w/extensions/SemanticMediaWiki/src/Maintenance/DataRebuilder.php(147): SMW\Maintenance\DataRebuilder->doRebuildAll()
#17 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(141): SMW\Maintenance\DataRebuilder->rebuild()
#18 /.../w/maintenance/doMaintenance.php(103): SMW\Maintenance\RebuildData->execute()
#19 /.../w/extensions/SemanticMediaWiki/maintenance/rebuildData.php(174): require_once(string)
#20 {main}
```

**Comment by kghbln** [comment]
> undisclosed wiki with this issue: Clearing I10n_cache did not help since this table was empty from the start. The particular and only file creating this issue was just uploaded and then embedded on a wiki page [[File:Xyz....]] as well as an link to [[Media:Xyz...]] was added to the same page.

Unsuccessfully tried to recreate the issue on [sandbox.smw.o](http://sandbox.semantic-mediawiki.org/wiki/Issue/4/SESP)

**Comment by mwjames** [comment]
> Unsuccessfully tried to recreate the issue on sandbox.smw.o

Please remember that on the sandbox #56 is alive which means if for some reason "it is a namespace -1" is detected, we bail out.

> The difference there it was a pdf-file on MW 1.23.13 here it is a jpg.file on 1.25.5.

We could explicitly try to filter NS_MEDIA by

```php
	public function newWikiPage( Title $title ) {

		// Fight a possible DB corruption and avoid "NS_MEDIA is a virtual namespace; use NS_FILE"
		if ( $title->getNamespace() === NS_MEDIA ) {
			$title = Title::makeTitleSafe(
				$title->getDBkey(),
				NS_FILE,
				$title->getInterwiki(),
				$title->getFragment()
			);
		}

		return \WikiPage::factory( $title );
	}
```

I would not be surprised if MW's `page` table holds a `-2` for the mentioned file (PDF).

Could you try figure out how many entries on smw.org contains either a namespace `-1` or `-2` in the `page` and `smw_object_ids` table.

PS: https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/a3aeffebcf5b2879f85bde8205a3a78e1f8c8b99/includes/datavalues/SMW_DV_WikiPage.php has two references to NS_MEDIA (maybe needs some follow up).

**Comment by kghbln** [comment]
Finally:

``SELECT * FROM `smw_object_ids` WHERE `smw_namespace` = -1``

result: 124 rows

``SELECT * FROM `smw_object_ids` WHERE `smw_namespace` = -2``

result: 53 rows

``SELECT * FROM `page` WHERE page_namespace = -1``
``SELECT * FROM `page` WHERE page_namespace = -2``

no result in both cases

**Comment by mwjames** [comment]
> SELECT * FROM `smw_object_ids` WHERE `smw_namespace` = -1
> result: 124 rows

Well, according to the MW docu we should not see -1 in the DB but since we do and `WikiPage` has a strict check it is no surprise that we see it jump like a rabbit on fire.
